### PR TITLE
[WIP] Codewind guide for VS Code and Codewind guide for Eclipse

### PR DESCRIPTION
**Pull request by j-c-berger**
Signed-off-by: Jacob Berger <jacob.berger@ibm.com>

### CODE REVIEW

**Review by jantley-ibm — COMMENTED** [review]
Hi Jake - Andrew is setting up the file names to match the folder names, so your file names should be:
codewind-getting-started-eclipse.md
codewind-getting-started-vscode.md
You can push the changes to this same PR.  Will review file contents then.

**Comment by j-c-berger** [comment]
@jantley-ibm, thanks for the heads up, and will do. I'll push a new commit with the proper file names and necessary changes to the docs themselves.

**Comment by alohr51** [comment]
Also if it's a WIP it should be going into the `draft` folder, looks like this PR is just putting it on the root of the repo.

**Comment by j-c-berger** [comment]
@alohr51, thanks for the clarification. As Jeff requested, I'll make the new subfolders containing the new guides. But I'll save it under the `draft` folder.

**Comment by j-c-berger** [comment]
@jantley-ibm, see new commit, thanks!

**Review by jantley-ibm — APPROVED** [review]

**Comment by alohr51** [comment]
@j-c-berger there were 3 `.DS_Store` files added in the PR could you open a new one that removes them? They should've bene added to a `.gitignore` file so that's my bad

**Comment by j-c-berger** [comment]
@alohr51, no worries. I made a new PR, #7 

I believe I removed them all. Let me know if not, thanks.

**Pull request merged**
